import java.time.DayOfWeek
import java.time.LocalTime

var mockMineral = mutableListOf(
    Mineral("Amethyst", Luster.VITREOUSGLASSY, Color.PURPLE, Hardness(7.0), Fracture.CONCHOIDAL),
    Mineral("Garnet", Luster.VITREOUSRESINOUS, Color.VARYING, Hardness(6.5, 7.5), Fracture.CONCHOIDAL),
    Mineral("Kyanite", Luster.VITREOUSPEARLY, Color.BLUE, Hardness(5.0, 7.0), Fracture.SPLINTERY),
    Mineral("Cinnabar", Luster.ADAMINTINE, Color.RED, Hardness(2.5), Fracture.UNEVEN),
    Mineral("Diamond", Luster.ADAMINTINE, Color.VARYING, Hardness(10.0), Fracture.CONCHOIDAL),
    Mineral("Gypsum", Luster.VITREOUSPEARLYSILKY, Color.VARYING, Hardness(7.0), Fracture.FIBROUS),
    Mineral("Copper", Luster.METALLIC, Color.COLORLESS, Hardness(2.5, 3.0), Fracture.HACKLY),
    Mineral("Muscovite", Luster.VITREOUSPEARLYSILKY, Color.COLORLESS, Hardness(2.0, 2.5), Fracture.UNEVEN),
    Mineral("Aragonite", Luster.VITREOUS, Color.WHITEYELLOW, Hardness(3.5, 4.0), Fracture.SUBCONCHOIDAL),
    Mineral("Talc", Luster.PEARLYGREASY, Color.WHITEGREEN, Hardness(1.0), Fracture.UNEVEN),
)

var mockLocation = mutableListOf(
    Location("Cairo", "A bit sandy",GeoPoint(30.0444, 31.2357)),   // Egypt
    Location("Oslo", "Surrounded by fjords and forests", GeoPoint(59.9139, 10.7522), "Does anyone really live here?"),   // Norway
    Location("Reykjavik", "Volcanic landscapes and hot springs", GeoPoint(64.1355, -21.8954)),  // Iceland),
    Location("Sydney", "Coastal city with sandstone geology", GeoPoint(-33.8688, 151.2093)), // Australia
    Location("Santiago", "At the foothills of the Andes", GeoPoint(-33.4489, -70.6693), "Shouldn't be chilly.") // Chile
)

// Generated by chatGPT
val mockEmployee = mutableListOf(
    Employee(
        employeeId = 1,
        name = Name("Alice", "Berg"),
        phoneNumber = "12345678",
        hourlyWage = 250.0,
        work = mutableListOf(
            Work(DayOfWeek.MONDAY, Location("Oslo", "Capital city", GeoPoint(59.91, 10.75)), LocalTime.of(9, 0), LocalTime.of(17, 0))
        )
    ),
    Employee(
        employeeId = 2,
        name = Name("Bjørn", "Hansen"),
        phoneNumber = "87654321",
        hourlyWage = 270.0,
        work = mutableListOf(
            Work(DayOfWeek.TUESDAY, Location("Trondheim", "Tech hub", GeoPoint(63.43, 10.39)), LocalTime.of(8, 0), LocalTime.of(16, 0))
        )
    ),
    Employee(
        employeeId = 3,
        name = Name("Clara", "Nilsen"),
        phoneNumber = "11223344",
        hourlyWage = 300.0,
        work = mutableListOf(
            Work(DayOfWeek.WEDNESDAY, Location("Bergen", "Rainy city", GeoPoint(60.39, 5.32)), LocalTime.of(10, 0), LocalTime.of(18, 0))
        )
    ),
    Employee(
        employeeId = 4,
        name = Name("David", "Olsen"),
        phoneNumber = "44332211",
        hourlyWage = 260.0,
        work = mutableListOf(
            Work(DayOfWeek.THURSDAY, Location("Stavanger", "Oil capital", GeoPoint(58.97, 5.73)), LocalTime.of(7, 30), LocalTime.of(15, 30))
        )
    ),
    Employee(
        employeeId = 5,
        name = Name("Emma", "Johansen"),
        phoneNumber = "99887766",
        hourlyWage = 280.0,
        work = mutableListOf(
            Work(DayOfWeek.FRIDAY, Location("Lillehammer", "Winter sports city", GeoPoint(61.12, 10.47)), LocalTime.of(9, 0), LocalTime.of(17, 0))
        )
    )
)